apiVersion: otus.otus.homework/v1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-sample
spec:
  # TODO(user): Add fields here
